services:
  database:
    container_name: database
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WealthWise
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wealthwise

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - wealthwise
    depends_on:
      - database

  backend:
    container_name: backend
    image: springboot:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /app/src
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/WealthWise
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - database
    networks:
      - wealthwise

  frontend:
    container_name: frontend
    image: nextjs:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
          target: /app/package.json
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wealthwise

volumes:
  pgdata:

networks:
  wealthwise: