server:
  port: 8080

logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        security: DEBUG

info:
  application:
    name: WealthWise
    description: Spring Boot Backend Application for WealthWise
    author: Team8

spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

plaid:
  client_id: 673bd095ba8af0001ac2617a
  secret: 79ac4231fa32f93df25b016605f174
  environment: sandbox
---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      connection:
        autocommit: false
      ddl-auto: update
    show-sql: true